require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.4'
prepare_react_native_project!

target 'PixelTv' do
  flags = get_default_flags()

  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => false,
    :fabric_enabled => false,
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'PixelTvTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      '../node_modules/react-native',
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
  end
end