# fly.toml app configuration file generated for pixeltv-api on 2025-06-22T14:14:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pixeltv-api'
primary_region = 'arn'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[cron]]
schedule = "15 12 * * *"
command = "npx ts-node scripts/import-videos-onserver.ts"

[[cron]]
schedule = "20 12 * * *"
command = "node dist/scripts/clean-quotes-inDB.ts"

[[cron]]
schedule = "15 16 * * *"
command = "node dist/scripts/import-videos-onserver.ts"

[[cron]]
schedule = "20 16 * * *"
command = "node dist/scripts/clean-quotes-inDB.ts"

