buildscript {
    ext {
        buildToolsVersion    = "33.0.0"
        minSdkVersion        = 21
        compileSdkVersion    = 34
        targetSdkVersion     = 34
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Android Gradle Plugin matching compileSdkVersion 34
        classpath("com.android.tools.build:gradle:8.1.1")
        // (Optional) if you use Google services
        classpath("com.google.gms:google-services:4.3.10")
    }
}

